name: Build Steam Link

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 1

      - name: Checkout Steam Link SDK
        uses: actions/checkout@v4
        with:
          repository: ValveSoftware/steamlink-sdk
          path: steamlink-sdk
          fetch-depth: 1

      - name: Set CI version
        run: |
          CI_VERSION=`echo $GITHUB_SHA | cut -c1-6`
          echo "CI_VERSION=$CI_VERSION" >> $GITHUB_ENV

      - name: Build binaries
        run: STEAMLINK_SDK_PATH=$PWD/steamlink-sdk scripts/build-steamlink-app.sh

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: Moonlight-SteamLink-${{ env.CI_VERSION }}
          path: build/deploy-release/*
          if-no-files-found: error
